/**
 * Client-safe article + YouTube link index (precomputed; no Wayback / scrape payloads).
 *
 * Generated by `scripts/build-extra-links.mjs` → {@link ./extra-links.gen.ts}.
 */
import EXTRA_LINKS from "./extra-links.gen";

type ExtraLinkRow = {
  articleLink?: string;
  youtubeLink?: string;
};

type ExtraLinksFile = {
  byCoord: Record<string, ExtraLinkRow>;
  byTitle: Record<string, ExtraLinkRow>;
};

/**
 * Canonical title match key (collapses whitespace, lowercases) for sheet ↔ coord keys.
 */
export function normalizeProblemTitleForArchiveMatch(rawTitle: string): string {
  if (rawTitle.length === 0) return "";
  return rawTitle.replace(/\s+/g, " ").trim().toLowerCase();
}

/**
 * Aggressive title key (strips punctuation) for {@link ExtraLinksFile.byTitle} lookups.
 */
export function normalizeProblemTitleForLiveLinkMatch(rawTitle: string): string {
  if (rawTitle.length === 0) return "";
  return rawTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function composeCoordKey(stepNo: number, subStepNo: number, normalizedTitle: string): string {
  return `${stepNo}|${subStepNo}|${normalizedTitle}`;
}

export type ArchiveExtraLinks = {
  articleLink: string | null;
  youtubeLink: string | null;
};

const EXTRA = EXTRA_LINKS as ExtraLinksFile;

/**
 * Resolves article + youtube URLs for one sheet problem.
 *
 * Prefers title map for articles, coord map for YouTube when both exist.
 */
export function getArchiveExtraLinksForProblem(
  stepNo: number,
  subStepNo: number,
  sheetTitle: string,
): ArchiveExtraLinks {
  const byTitle = EXTRA.byTitle[normalizeProblemTitleForLiveLinkMatch(sheetTitle)];
  const byCoord =
    EXTRA.byCoord[
      composeCoordKey(stepNo, subStepNo, normalizeProblemTitleForArchiveMatch(sheetTitle))
    ];

  return {
    articleLink: byTitle?.articleLink ?? byCoord?.articleLink ?? null,
    youtubeLink: byCoord?.youtubeLink ?? byTitle?.youtubeLink ?? null,
  };
}
